Fix docs badge on README.rst
CMakePP/CMakeTest pull request #86
Opened 2023-07-08 21:01 UTC by AutonomicPerfectionist

**Is this pull request associated with an issue(s)?**
Fixes #84 

**Description**
This just changes the badge URL in the README.rst to the correct one for the docs action.

**Note**
Apparently, those URLs are based on the name of the workflow, so if we change the name we'd need to change these URLs again, even if the workflow filename remains the same

2023-07-09 14:21 UTC, zachcran requested changes
I think we want to change the URL to `https://github.com/CMakePP/CMakeTest/workflows/Build%20and%20Deploy%20Documentation/badge.svg`, removing the `?branch=master`. I checked both and when `?branch=master` is appended, the resulting image says "no status".

2023-07-09 14:45 UTC, AutonomicPerfectionist commented
Yep that makes sense, I'll get that changed as soon as possible

2023-07-09 17:25 UTC, AutonomicPerfectionist commented
I removed the query string but I decided to look at the documentation to see why it was there in the first image. Curiously, it seems there are two different URL schemes for badges, the documentation [here](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge) suggests to use the `.../actions/workflows/<filename>/badge.svg` and supports the query string, while the URL we're using (without the `actions` prefix and using the name of the workflow instead of the filename) appears to not support the query string. In fact, I can't seem to find any documentation at all on the second scheme

2023-07-10 13:31 UTC, ryanmrichard approved these changes

2023-07-10 13:59 UTC, zachcran approved these changes

2023-07-10 17:18 UTC, merged